// <auto-generated />
using System;
using System.Collections.Generic;
using MakesCentsToMe.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MakesCentsToMe.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331110609_AddCategoriesAndTransactionAnalysis")]
    partial class AddCategoriesAndTransactionAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            IsDefault = true,
                            Name = "Dining"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            IsDefault = true,
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            IsDefault = true,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            IsDefault = true,
                            Name = "Fees and Charges"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            IsDefault = true,
                            Name = "Gifts and Donations"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            IsDefault = true,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            IsDefault = true,
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            IsDefault = true,
                            Name = "Housing"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            IsDefault = true,
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000a"),
                            IsDefault = true,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000b"),
                            IsDefault = true,
                            Name = "Personal Care"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000c"),
                            IsDefault = true,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000d"),
                            IsDefault = true,
                            Name = "Transfer"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000e"),
                            IsDefault = true,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000f"),
                            IsDefault = true,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            IsDefault = true,
                            Name = "Uncategorized"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000011"),
                            IsDefault = true,
                            Name = "Utilities"
                        });
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.ColumnMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CsvColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ImportProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ImportProfileId");

                    b.ToTable("ColumnMappings");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.ImportProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AmountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BalanceProvided")
                        .HasColumnType("boolean");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("ImportProfiles");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Fees")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Interest")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("NormalizedVendor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Principal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("RawCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RawCsvRow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SuggestedCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SuggestedCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestedNormalizedVendor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Transactions_Status");

                    b.HasIndex("AccountId", "Date", "Description", "Amount")
                        .HasDatabaseName("IX_Transactions_Dedup");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.Account", b =>
                {
                    b.HasOne("MakesCentsToMe.Api.Models.Entities.Institution", "Institution")
                        .WithMany("Accounts")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.ColumnMapping", b =>
                {
                    b.HasOne("MakesCentsToMe.Api.Models.Entities.ImportProfile", null)
                        .WithMany("ColumnMappings")
                        .HasForeignKey("ImportProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.ImportProfile", b =>
                {
                    b.HasOne("MakesCentsToMe.Api.Models.Entities.Account", "Account")
                        .WithOne("ImportProfile")
                        .HasForeignKey("MakesCentsToMe.Api.Models.Entities.ImportProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.Transaction", b =>
                {
                    b.HasOne("MakesCentsToMe.Api.Models.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakesCentsToMe.Api.Models.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.Account", b =>
                {
                    b.Navigation("ImportProfile");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.ImportProfile", b =>
                {
                    b.Navigation("ColumnMappings");
                });

            modelBuilder.Entity("MakesCentsToMe.Api.Models.Entities.Institution", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
